import ROOT as r
import rootUtils as ut

""" Histograms and plots are defined here. """
h = {}

# Efficiencies Respect to Selections with Neutrino Energy
ut.bookHist(h, 'g-nuEff', 'Efficiency Plot #nu_{#mu}: Geometric Selection',    60, 0, 300)
ut.bookHist(h, 'l-nuEff', 'Efficiency Plot #nu_{#mu}: Location Selection',     60, 0, 300)
ut.bookHist(h, 'd-nuEff', 'Efficiency Plot #nu_{#mu}: Decay Search Selection', 60, 0, 300)
# DSS Efficiencies Respect Charm Flavor with Neutrino Energy
ut.bookHist(h, 'd-nuEff1', 'Efficiency Plot #nu_{#mu}: Decay Search Selection', 60, 0, 300)
ut.bookHist(h, 'd-nuEff2', 'Efficiency Plot #nu_{#mu}: Decay Search Selection', 60, 0, 300)
ut.bookHist(h, 'd-nuEff3', 'Efficiency Plot #nu_{#mu}: Decay Search Selection', 60, 0, 300)
ut.bookHist(h, 'd-nuEff4', 'Efficiency Plot #nu_{#mu}: Decay Search Selection', 60, 0, 300)

def makePlots():

  # Incoming Neutrino Beam Energy After Selections
  ut.bookCanvas(h,key='CnuE',title='Incoming Neutrino Beam Energy',nx=2880,ny=540,cx=3,cy=1)
  r.gStyle.SetOptStat('mr')
  cv = h['CnuE'].cd(1)
  h['nuE'].Draw()
  h['nuE'].SetXTitle('Energy (GeV)')
  r.gPad.Update()
  sBox_nuE = h['nuE'].FindObject('stats')
  sBox_nuE.SetY1NDC(0.8)
  sBox_nuE.SetY2NDC(0.7)
  h['g-nuEs'].SetFillStyle(3335)
  h['g-nuEs'].SetFillColor(2)
  h['g-nuEs'].Draw('SAMES')
  cv = h['CnuE'].cd(2)
  h['nuE'].Draw()
  h['nuE'].SetXTitle('Energy (GeV)')
  h['l-nuEs'].SetFillStyle(3335)
  h['l-nuEs'].SetFillColor(2)
  h['l-nuEs'].Draw('SAMES')
  cv = h['CnuE'].cd(3)
  h['nuE'].Draw()
  h['nuE'].SetXTitle('Energy (GeV)')
  h['d-nuEs'].SetFillStyle(3335)
  h['d-nuEs'].SetFillColor(2)
  h['d-nuEs'].Draw('SAMES')
  h['CnuE'].Print(work_dir+'/Histograms/CnuE.pdf')

  # Efficiencies Respect to Selections with Neutrino Energy
  ut.bookCanvas(h,key='CnuEff',title='Efficiency Plot',nx=2880,ny=540,cx=3,cy=1)
  r.gStyle.SetOptStat(0)
  cv = h['CnuEff'].cd(1)
  h['nuE'].Draw()
  h['g-nuEs'].Draw()
  h['g-nuEs'].Sumw2()
  h['g-nuEff'].Divide(h['g-nuEs'],h['nuE'],1.,1.,'B')
  h['g-nuEff'].Draw('E0')
  h['g-nuEff'].SetXTitle('Energy (GeV)')
  cv = h['CnuEff'].cd(2)
  h['nuE'].Draw()
  h['l-nuEs'].Draw()
  h['l-nuEs'].Sumw2()
  h['l-nuEff'].Divide(h['l-nuEs'],h['nuE'],1.,1.,'B')
  h['l-nuEff'].Draw('E0')
  h['l-nuEff'].SetXTitle('Energy (GeV)')
  cv = h['CnuEff'].cd(3)
  h['nuE'].Draw()
  h['d-nuEs'].Draw()
  h['d-nuEs'].Sumw2()
  h['d-nuEff'].Divide(h['d-nuEs'],h['nuE'],1.,1.,'B')
  h['d-nuEff'].Draw('E0')
  h['d-nuEff'].SetXTitle('Energy (GeV)')
  h['CnuEff'].Print(work_dir+'/Histograms/CnuEff.pdf')

  # Incoming Neutrino Beam Energy Respect to Induced Charm Flavor
  ut.bookCanvas(h,key='CnuEX',title='Incoming Neutrino Beam Energy',nx=1920,ny=1080,cx=2,cy=2)
  r.gStyle.SetOptStat('mr')
  cv = h['CnuEX'].cd(1)
  h['nuE1'].Draw()
  h['nuE1'].SetXTitle('Energy (GeV)')
  r.gPad.Update()
  sBox_nuE = h['nuE1'].FindObject('stats')
  sBox_nuE.SetY1NDC(0.8)
  sBox_nuE.SetY2NDC(0.7)
  h['d-nuEs1'].SetFillStyle(3335)
  h['d-nuEs1'].SetFillColor(2)
  h['d-nuEs1'].Draw('SAMES')
  cv = h['CnuEX'].cd(2)
  h['nuE2'].Draw()
  h['nuE2'].SetXTitle('Energy (GeV)')
  h['d-nuEs2'].SetFillStyle(3335)
  h['d-nuEs2'].SetFillColor(2)
  h['d-nuEs2'].Draw('SAMES')
  cv = h['CnuEX'].cd(3)
  h['nuE3'].Draw()
  h['nuE3'].SetXTitle('Energy (GeV)')
  h['d-nuEs3'].SetFillStyle(3335)
  h['d-nuEs3'].SetFillColor(2)
  h['d-nuEs3'].Draw('SAMES')
  cv = h['CnuEX'].cd(4)
  h['nuE4'].Draw()
  h['nuE4'].SetXTitle('Energy (GeV)')
  h['d-nuEs4'].SetFillStyle(3335)
  h['d-nuEs4'].SetFillColor(2)
  h['d-nuEs4'].Draw('SAMES')
  h['CnuEX'].Print(work_dir+'/Histograms/CnuEX.pdf')

  # DSS Efficiencies Respect Charm Flavor with Neutrino Energy
  ut.bookCanvas(h,key='CnuEffCF',title='Efficiency Plot',nx=1920,ny=1080,cx=2,cy=2)
  r.gStyle.SetOptStat(0)
  cv = h['CnuEffCF'].cd(1)
  h['nuE1'].Draw()
  h['d-nuEs1'].Draw()
  h['d-nuEs1'].Sumw2()
  h['d-nuEff1'].Divide(h['d-nuEs1'],h['nuE1'],1.,1.,'B')
  h['d-nuEff1'].Draw('E0')
  h['d-nuEff1'].SetXTitle('Energy (GeV)')
  cv = h['CnuEffCF'].cd(2)
  h['nuE2'].Draw()
  h['d-nuEs2'].Draw()
  h['d-nuEs2'].Sumw2()
  h['d-nuEff2'].Divide(h['d-nuEs2'],h['nuE2'],1.,1.,'B')
  h['d-nuEff2'].Draw('E0')
  h['d-nuEff2'].SetXTitle('Energy (GeV)')
  cv = h['CnuEffCF'].cd(3)
  h['nuE3'].Draw()
  h['d-nuEs3'].Draw()
  h['d-nuEs3'].Sumw2()
  h['d-nuEff3'].Divide(h['d-nuEs3'],h['nuE3'],1.,1.,'B')
  h['d-nuEff3'].Draw('E0')
  h['d-nuEff3'].SetXTitle('Energy (GeV)')
  cv = h['CnuEffCF'].cd(4)
  h['nuE4'].Draw()
  h['d-nuEs4'].Draw()
  h['d-nuEs4'].Sumw2()
  h['d-nuEff4'].Divide(h['d-nuEs4'],h['nuE4'],1.,1.,'B')
  h['d-nuEff4'].Draw('E0')
  h['d-nuEff4'].SetXTitle('Energy (GeV)')
  h['CnuEffCF'].Print(work_dir+'/Histograms/CnuEffCF.pdf')

  #Multiplicity at Neutrino Vertex Histograms
  ut.bookCanvas(h,key='dMultAnalysis',title='Multiplicity at Neutrino Vertex',nx=1920,ny=1080,cx=2,cy=2)
  cv = h['dMultAnalysis'].cd(1)
  h['dC1M'].Draw()
  h['dC1MS'].SetFillStyle(3335)
  h['dC1MS'].SetFillColor(2)
  h['dC1MS'].Draw('same')
  cv = h['dMultAnalysis'].cd(2)
  h['dC2M'].Draw()
  h['dC2MS'].SetFillStyle(3335)
  h['dC2MS'].SetFillColor(2)
  h['dC2MS'].Draw('same')
  cv = h['dMultAnalysis'].cd(3)
  h['dC3M'].Draw()
  h['dC3MS'].SetFillStyle(3335)
  h['dC3MS'].SetFillColor(2)
  h['dC3MS'].Draw('same')
  cv = h['dMultAnalysis'].cd(4)
  h['dC4M'].Draw()
  h['dC4MS'].SetFillStyle(3335)
  h['dC4MS'].SetFillColor(2)
  h['dC4MS'].Draw('same')
  h['dMultAnalysis'].Print(work_dir+'/Histograms/dcmult.pdf')

  #Multiplicity at Charm Vertex Histograms
  ut.bookCanvas(h,key='dMultAnalysis2',title='Multiplicity at Charm Vertex',nx=1920,ny=1080,cx=2,cy=2)
  cv = h['dMultAnalysis2'].cd(1)
  h['dC1M2'].Draw()
  h['dC1M2S'].SetFillStyle(3335)
  h['dC1M2S'].SetFillColor(2)
  h['dC1M2S'].Draw('same')
  cv = h['dMultAnalysis2'].cd(2)
  h['dC2M2'].Draw()
  h['dC2M2S'].SetFillStyle(3335)
  h['dC2M2S'].SetFillColor(2)
  h['dC2M2S'].Draw('same')
  cv = h['dMultAnalysis2'].cd(3)
  h['dC3M2'].Draw()
  h['dC3M2S'].SetFillStyle(3335)
  h['dC3M2S'].SetFillColor(2)
  h['dC3M2S'].Draw('same')
  cv = h['dMultAnalysis2'].cd(4)
  h['dC4M2'].Draw()
  h['dC4M2S'].SetFillStyle(3335)
  h['dC4M2S'].SetFillColor(2)
  h['dC4M2S'].Draw('same')
  h['dMultAnalysis2'].Print(work_dir+'/Histograms/dcmult2.pdf')

  #Bjorken X distribution
  ut.bookCanvas(h,key='bjor',title='Bjorken X Distribution',nx=1920,ny=1080,cx=1,cy=1)
  cv = h['bjor'].cd(1)
  h['BjorX'].Draw()
  h['BjorXs'].SetFillStyle(3335)
  h['BjorXs'].SetFillColor(2)
  h['BjorXs'].Draw('same')
  h['bjor'].Print(work_dir+'/Histograms/bjorkenX.pdf')

  #Inelasticity Y distribution
  ut.bookCanvas(h,key='inel',title='Inelasticity Y Distribution',nx=1920,ny=1080,cx=1,cy=1)
  cv = h['inel'].cd(1)
  h['InelY'].Draw()
  h['InelYs'].SetFillStyle(3335)
  h['InelYs'].SetFillColor(2)
  h['InelYs'].Draw('same')
  h['inel'].Print(work_dir+'/Histograms/inelasticityY.pdf')

  # Neutrino Interaction Points in X-Y-Z
  ut.bookCanvas(h,key='nutp',title='Transverse Plane Interactions',nx=1920,ny=720,cx=2,cy=1)
  cv = h['nutp'].cd(1)
  h['tp'].Draw('COLZ')
  cv = h['nutp'].cd(2)
  h['tpS'].Draw('COLZ')
  h['nutp'].Print(work_dir+'/Histograms/nutplane.pdf')
  ut.bookCanvas(h,key='zaxis',title='Z Axis Interactions',nx=1920,ny=1080,cx=1,cy=1)
  cv = h['zaxis'].cd(1)
  h['za'].Draw()
  h['zaS'].SetFillStyle(3335)
  h['zaS'].SetFillColor(2)
  h['zaS'].Draw('same')
  h['zaxis'].Print(work_dir+'/Histograms/nuZ.pdf')

  #Angular Distribution of Neutrinos X-Y Scatter Plot
  ut.bookCanvas(h,key='CnuAng2D',title='Angular Distribution X-Y Scatter Plot',nx=1920,ny=1080,cx=2,cy=1)
  r.gStyle.SetOptStat(1111)
  cv = h['CnuAng2D'].cd(1)
  h['nuAng2DF'].Draw('COLZ')
  h['nuAng2DF'].SetXTitle('mrad')
  h['nuAng2DF'].SetYTitle('mrad')
  cv = h['CnuAng2D'].cd(2)
  h['d-nuAng2DFs'].Draw('COLZ')
  h['d-nuAng2DFs'].SetXTitle('mrad')
  h['d-nuAng2DFs'].SetYTitle('mrad')
  h['CnuAng2D'].Print(work_dir+'/Histograms/CnuAng2D.pdf')

  # Charmed Hadron Energy Spectrum
  ut.bookCanvas(h,key='dEnergyAnalysis',title='Produced Charmed Hadron Energies',nx=1920,ny=1080,cx=2,cy=2)
  cv = h['dEnergyAnalysis'].cd(1)
  r.gStyle.SetOptStat(1111)
  h['dC1E'].Draw()
  h['dC1E'].SetXTitle('Energy (GeV)')
  h['dC1ES'].SetFillStyle(3335)
  h['dC1ES'].SetFillColor(2)
  h['dC1ES'].Draw('same')
  cv = h['dEnergyAnalysis'].cd(2)
  h['dC2E'].Draw()
  h['dC2E'].SetXTitle('Energy (GeV)')
  h['dC2ES'].SetFillStyle(3335)
  h['dC2ES'].SetFillColor(2)
  h['dC2ES'].Draw('same')
  cv = h['dEnergyAnalysis'].cd(3)
  h['dC3E'].Draw()
  h['dC3E'].SetXTitle('Energy (GeV)')
  h['dC3ES'].SetFillStyle(3335)
  h['dC3ES'].SetFillColor(2)
  h['dC3ES'].Draw('same')
  cv = h['dEnergyAnalysis'].cd(4)
  h['dC4E'].Draw()
  h['dC4E'].SetXTitle('Energy (GeV)')
  h['dC4ES'].SetFillStyle(3335)
  h['dC4ES'].SetFillColor(2)
  h['dC4ES'].Draw('same')
  h['dEnergyAnalysis'].Print(work_dir+'/Histograms/dcenergy.pdf')

  # Charmed Hadron Flight Length
  ut.bookCanvas(h,key='dFLAnalysis',title='Produced Charmed Hadron Flight Lengths',nx=1920,ny=1080,cx=2,cy=2)
  cv = h['dFLAnalysis'].cd(1)
  h['dC1FL'].Draw()
  h['dC1FL'].SetXTitle('Decay Length (mm)')
  h['dC1FLS'].SetFillStyle(3335)
  h['dC1FLS'].SetFillColor(2)
  h['dC1FLS'].Draw('same')
  cv = h['dFLAnalysis'].cd(2)
  h['dC2FL'].Draw()
  h['dC2FL'].SetXTitle('Decay Length (mm)')
  h['dC2FLS'].SetFillStyle(3335)
  h['dC2FLS'].SetFillColor(2)
  h['dC2FLS'].Draw('same')
  cv = h['dFLAnalysis'].cd(3)
  h['dC3FL'].Draw()
  h['dC3FL'].SetXTitle('Decay Length (mm)')
  h['dC3FLS'].SetFillStyle(3335)
  h['dC3FLS'].SetFillColor(2)
  h['dC3FLS'].Draw('same')
  cv = h['dFLAnalysis'].cd(4)
  h['dC4FL'].Draw()
  h['dC4FL'].SetXTitle('Decay Length (mm)')
  h['dC4FLS'].SetFillStyle(3335)
  h['dC4FLS'].SetFillColor(2)
  h['dC4FLS'].Draw('same')
  h['dFLAnalysis'].Print(work_dir+'/Histograms/dcfl.pdf')

  # Charmed Hadron Impact Parameter
  ut.bookCanvas(h,key='dIPAnalysis',title='Produced Charmed Hadron Impact Parameters',nx=1920,ny=1080,cx=2,cy=2)
  cv = h['dIPAnalysis'].cd(1)
  h['dC1IP'].Draw()
  h['dC1IP'].SetXTitle('Decay Length (#mum)')
  h['dC1IPS'].SetFillStyle(3335)
  h['dC1IPS'].SetFillColor(2)
  h['dC1IPS'].Draw('same')
  cv = h['dIPAnalysis'].cd(2)
  h['dC2IP'].Draw()
  h['dC2IP'].SetXTitle('Decay Length (#mum)')
  h['dC2IPS'].SetFillStyle(3335)
  h['dC2IPS'].SetFillColor(2)
  h['dC2IPS'].Draw('same')
  cv = h['dIPAnalysis'].cd(3)
  h['dC3IP'].Draw()
  h['dC3IP'].SetXTitle('Decay Length (#mum)')
  h['dC3IPS'].SetFillStyle(3335)
  h['dC3IPS'].SetFillColor(2)
  h['dC3IPS'].Draw('same')
  cv = h['dIPAnalysis'].cd(4)
  h['dC4IP'].Draw()
  h['dC4IP'].SetXTitle('Decay Length (#mum)')
  h['dC4IPS'].SetFillStyle(3335)
  h['dC4IPS'].SetFillColor(2)
  h['dC4IPS'].Draw('same')
  h['dIPAnalysis'].Print(work_dir+'/Histograms/dcip.pdf')

  # Charmed Hadron Kink and Opening Angle
  ut.bookCanvas(h,key='kAngle',title='Kink Angle',nx=1920,ny=540,cx=3,cy=1)
  cv = h['kAngle'].cd(1)
  h['dC1KA'].Draw()
  h['dC1KA'].SetXTitle('Kink Angle (rad)')
  h['dC1KAS'].SetFillStyle(3335)
  h['dC1KAS'].SetFillColor(2)
  h['dC1KAS'].Draw('same')
  cv = h['kAngle'].cd(2)
  h['dC3KA'].Draw()
  h['dC3KA'].SetXTitle('Kink Angle (rad)')
  h['dC3KAS'].SetFillStyle(3335)
  h['dC3KAS'].SetFillColor(2)
  h['dC3KAS'].Draw('same')
  cv = h['kAngle'].cd(3)
  h['dC4KA'].Draw()
  h['dC4KA'].SetXTitle('Kink Angle (rad)')
  h['dC4KAS'].SetFillStyle(3335)
  h['dC4KAS'].SetFillColor(2)
  h['dC4KAS'].Draw('same')
  h['kAngle'].Print(work_dir+'/Histograms/kAngle.pdf')
  ut.bookCanvas(h,key='oAngle',title='Opening Angle',nx=1920,ny=1080,cx=1,cy=1)
  cv = h['oAngle'].cd(1)
  h['dC2OA'].Draw()
  h['dC2OA'].SetXTitle('Opening Angle (rad)')
  h['dC2OAS'].SetFillStyle(3335)
  h['dC2OAS'].SetFillColor(2)
  h['dC2OAS'].Draw('same')
  h['oAngle'].Print(work_dir+'/Histograms/oAngle.pdf')
