executable = /afs/cern.ch/user/e/eelikkay/NICPStudies/htcondor/geant/above/geant.sh
arguments = $(ClusterId) $(ProcId) tau 16 10000

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/geant/tau/above/$(ClusterId)_$(ProcId).out
error  = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/geant/tau/above/$(ClusterId)_$(ProcId).err
log    = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/geant/tau/above/$(ClusterId)_$(ProcId).log

requirements= (CERNEnvironment =!= "qa")
+JobFlavour = "nextweek"

request_cpus = 1
request_disk = 90MB
request_memory = 500MB

queue 150
