executable = /afs/cern.ch/user/e/eelikkay/NICPStudies/htcondor/geant/tungsten/above/geant.sh
arguments = $(ClusterId) $(ProcId) mu 14 8923

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
getenv = true

output = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/geant/tungsten/mu/above/$(ClusterId)_$(ProcId).out
error  = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/geant/tungsten/mu/above/$(ClusterId)_$(ProcId).err
log    = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/geant/tungsten/mu/above/$(ClusterId)_$(ProcId).log

requirements= (CERNEnvironment =!= "qa")
+JobFlavour = "nextweek"

request_cpus = 1
request_disk = 90MB
request_memory = 500MB

queue 150
