executable = /afs/cern.ch/user/e/eelikkay/NICPStudies/htcondor/gntpc/gntpc.sh
arguments = 9571803 $(ProcId) e 12

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/gntpc/e/$(ClusterId)_$(ProcId).out
error  = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/gntpc/e/$(ClusterId)_$(ProcId).err
log    = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/gntpc/e/$(ClusterId)_$(ProcId).log

requirements= (CERNEnvironment =!= "qa")
+JobFlavour = "nextweek"

request_cpus = 1
request_disk = 20KB
request_memory = 1MB

queue 150
