executable = /afs/cern.ch/user/e/eelikkay/NICPStudies/HTC_Weight/weight_mu.sh
arguments = $(ClusterId) $(ProcId)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs-HTC_Weight/stdout/nu_mu-$(ClusterId)_$(ProcId).out
error  = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs-HTC_Weight/stderr/nu_mu-$(ClusterId)_$(ProcId).err
log    = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs-HTC_Weight/htclog/nu_mu-$(ClusterId)_$(ProcId).log

requirements= (CERNEnvironment =!= "qa")
+JobFlavour = "nextweek"

request_cpus = 1
request_disk = 1536KB
request_memory = 70MB

queue 130
