executable = /afs/cern.ch/user/e/eelikkay/NICPStudies/HTC_Genie/genieAbove_tau_bar.sh
arguments = $(ClusterId) $(ProcId)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs-HTC_Genie/stdout/nu_tau_bar-above-$(ClusterId)_$(ProcId).out
error  = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs-HTC_Genie/stderr/nu_tau_bar-above-$(ClusterId)_$(ProcId).err
log    = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs-HTC_Genie/htclog/nu_tau_bar-above-$(ClusterId)_$(ProcId).log

requirements= (CERNEnvironment =!= "qa")
+JobFlavour = "nextweek"

request_cpus = 1
request_disk = 55MB
request_memory = 130MB

queue 130
