executable = /afs/cern.ch/user/e/eelikkay/NICPStudies/htcondor/genie/genie.sh
arguments = $(ClusterId) $(ProcId) mu 14

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

output = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/genie/mu/$(ClusterId)_$(ProcId).out
error  = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/genie/mu/$(ClusterId)_$(ProcId).err
log    = /afs/cern.ch/work/e/eelikkay/NICPStudies/logs/genie/mu/$(ClusterId)_$(ProcId).log

requirements= (CERNEnvironment =!= "qa")
+JobFlavour = "nextweek"

request_cpus = 1
request_disk = 45MB
request_memory = 90MB

queue 150
